### ISSUE TITLE
Crash when starting docker : ClassNotFoundException

### ISSUE THREAD

**Issue by grizio** [camunda-community-hub/zeebe-docker-compose#41]
When I want to start the zeebe container, I have a crash.

Steps to reproduce (with docker on Windows):

```
git clone git@github.com:zeebe-io/zeebe-docker-compose.git
cd zeebe-docker-compose
cd operate-simple-monitor
docker-compose up
```

At some point, I got:

```
zeebe            | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
zeebe            | 2021-05-27 13:25:43.542 [] [main] ERROR
zeebe            |       org.springframework.boot.SpringApplication - Application run failed
zeebe            | java.lang.NoClassDefFoundError: io/zeebe/exporter/api/Exporter
zeebe            |      at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
zeebe            |      at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
zeebe            |      at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
zeebe            |      at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:?]
zeebe            |      at java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
zeebe            |      at java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
zeebe            |      at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
zeebe            |      at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
zeebe            |      at io.camunda.zeebe.broker.exporter.jar.ExporterJarClassLoader.loadClass(ExporterJarClassLoader.java:58) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:78) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:435) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.lambda$partitionsStep$21(Broker.java:408) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:423) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.lambda$initStart$10(Broker.java:234) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.0.0.jar:1.0.0]
zeebe            |      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar:2.4.5]
zeebe            |      at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar:2.4.5]
zeebe            |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar:2.4.5]
zeebe            |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar:2.4.5]
zeebe            |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar:2.4.5]
zeebe            |      at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [camunda-cloud-zeebe-1.0.0.jar:1.0.0]
zeebe            | Caused by: java.lang.ClassNotFoundException: io.zeebe.exporter.api.Exporter
zeebe            |      at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
zeebe            |      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe            |      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe            |      at io.camunda.zeebe.broker.exporter.jar.ExporterJarClassLoader.loadClass(ExporterJarClassLoader.java:60) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe            |      ... 34 more
```

The jar in `lib/zeebe-hazelcast-exporter-0.10.0.jar` does not contains the specified class but should it be this jar that should contain it?

Thanks for your repository. 🙏

**Comment by grizio** [comment]
It seems to come from the lib `zeebe-hazelcast-exporter-0.10.0.jar` that should be in version 1.0.0. When testing it by downloading the version here https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.0.0 , it works.

Should I create a PR by updating the library with this jar + configurations files ?

**Comment by jwulf** [comment]
Thanks for reporting this @grizio 

> Should I create a PR by updating the library with this jar + configurations files ?

Yes please, that would be awesome!
